DROP TABLE IF EXISTS signatures;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_profile;

CREATE TABLE signatures (
  id SERIAL PRIMARY KEY,
  user_id INTEGER,
  signature text NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE users (

  id SERIAL PRIMARY KEY,
  first VARCHAR(300) NOT NULL,
  last VARCHAR(300) NOT NULL,
  email VARCHAR(300) UNIQUE NOT NULL,
  password CHAR(60) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_profiles (

  id SERIAL PRIMARY KEY,
  user_id INTEGER UNIQUE NOT NULL,
  age INTEGER,
  city VARCHAR(300),
  url VARCHAR(300),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
